language: python
sudo: false
branches:
  only:
    - master
python:
  - "2.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --yes conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=2.7 nose numpy scipy pytables pycrypto pyqt sip pygments pil
  - git clone https://github.com/tainstr/misura.canon.git ../misura.canon
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/../misura.canon
  - git clone https://github.com/tainstr/veusz.git ../veusz
  - export VEUSZ_RESOURCE_DIR=$(pwd)/../veusz
  - export PYTHONPATH=$PYTHONPATH:$VEUSZ_RESOURCE_DIR
  - source activate test-environment
  - pip install python-coveralls
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - source activate test-environment
  - which python
  - echo PYTHONPATH
  - python2.7 -c "import PyQt4; print 'PyQt4 OK'"
  - nosetests-2.7 -vv --with-coverage --cover-package=misura
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
after_success:
  - coveralls
