language: python


python:
  - "2.7"


before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --yes conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=2.7 nose numpy scipy pytables pycrypto pygments pil twisted pyserial
  - source activate test-environment
  - conda install --channel https://conda.anaconda.org/conda-forge pyqt=4.11.4 sip python-coveralls
  - git clone https://bitbucket.org/tainstr/misura.canon.git ../misura.canon
  - git clone https://bitbucket.org/tainstr/misura.droid.git ../misura.droid
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/../misura.canon
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/../misura.droid
  - git clone https://github.com/tainstr/veusz.git ../veusz
  - export VEUSZ_RESOURCE_DIR=$(pwd)/../veusz
  - export PYTHONPATH=$PYTHONPATH:$VEUSZ_RESOURCE_DIR
  # add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
script:
  - nosetests -vv --with-coverage --cover-package=misura --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_misura.client_7b86d77462_2
  - python -m properform Push 47.88.50.110:15554 asdf_misura.client_7b86d77462_2 ./profile_misura.client_7b86d77462_2


cache:
  - apt
  - directories:
    - $HOME/.cache/pip
after_success:
  - coveralls
 #2017-08-13 16:50:04 modified at 0 #2017-08-13 16:50:09 modified at 1 #2017-08-13 16:50:13 modified at 2