language: python
sudo: false
branches:
  only:
    - master
python:
  - "2.7"
install:
  - wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q --yes conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=2.7 nose numpy scipy pytables pycrypto pyqt pygments
  - git clone https://github.com/tainstr/misura.canon.git
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/misura.canon
  - git clone https://github.com/tainstr/veusz.git
  - export VEUSZ_RESOURCE_DIR=$(pwd)/veusz
  - export PYTHONPATH=$PYTHONPATH:$VEUSZ_RESOURCE_DIR
script:
  - source activate test-environment
  - nosetests
cache:
  - apt
  - directories:
    - $HOME/.cache/pip
